"""init_system_settings

Revision ID: 13b02a6d3db7
Revises: 56608622def2
Create Date: 2026-02-03 15:54:47.755027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b02a6d3db7'
down_revision: Union[str, Sequence[str], None] = '56608622def2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table exists to avoid error on restart
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table('system_settings'):
        op.create_table('system_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('download_settings', sa.JSON(), nullable=True),
        sa.Column('monitor_settings', sa.JSON(), nullable=True),
        sa.Column('notify_settings', sa.JSON(), nullable=True),
        sa.Column('metadata_settings', sa.JSON(), nullable=True),
        sa.Column('scheduler_settings', sa.JSON(), nullable=True),
        sa.Column('system_overrides', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
