"""Add cover to songs

Revision ID: 20b85a3c6d12
Revises: 13b02a6d3db7
Create Date: 2026-02-04 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b85a3c6d12'
down_revision: Union[str, Sequence[str], None] = '13b02a6d3db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # [Fix] Guard against duplicate column when Base.metadata.create_all
    # has already created the column (async_init_db runs create_all first).
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table('songs'):
        cols = [c['name'] for c in inspector.get_columns('songs')]
        if 'cover' not in cols:
            op.add_column('songs', sa.Column('cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'cover')
    # ### end Alembic commands ###
