"""Add compatibility columns to Song

Revision ID: 7caa34b35a43
Revises: da25a5e33b66
Create Date: 2026-01-21 12:07:29.705109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7caa34b35a43'
down_revision: Union[str, Sequence[str], None] = 'da25a5e33b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('url', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('is_pushed', sa.Boolean(), nullable=True))
    op.add_column('songs', sa.Column('push_time', sa.DateTime(), nullable=True))
    op.add_column('songs', sa.Column('audio_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'audio_quality')
    op.drop_column('songs', 'push_time')
    op.drop_column('songs', 'is_pushed')
    op.drop_column('songs', 'url')
    # ### end Alembic commands ###
