"""Initial tables

Revision ID: da25a5e33b66
Revises: 
Create Date: 2026-01-21 12:00:48.013798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da25a5e33b66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('media_id', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_index(op.f('ix_songs_unique_key'), 'songs', ['unique_key'], unique=True)
    # Check if table exists before dropping (support fresh install)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'media_records' in tables:
        op.drop_index(op.f('ix_media_records_unique_key'), table_name='media_records')
        op.drop_table('media_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_key', sa.VARCHAR(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('media_type', sa.VARCHAR(), nullable=False),
    sa.Column('media_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('cover', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('trial_url', sa.VARCHAR(), nullable=True),
    sa.Column('album', sa.VARCHAR(), nullable=True),
    sa.Column('publish_time', sa.DATETIME(), nullable=True),
    sa.Column('local_audio_path', sa.VARCHAR(), nullable=True),
    sa.Column('audio_quality', sa.INTEGER(), nullable=True),
    sa.Column('audio_size', sa.INTEGER(), nullable=True),
    sa.Column('lyrics', sa.TEXT(), nullable=True),
    sa.Column('lyrics_source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lyrics_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('found_at', sa.DATETIME(), nullable=True),
    sa.Column('is_pushed', sa.BOOLEAN(), nullable=True),
    sa.Column('push_time', sa.DATETIME(), nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_records_unique_key'), 'media_records', ['unique_key'], unique=1)
    op.drop_index(op.f('ix_songs_unique_key'), table_name='songs')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
