
import hmac
import hashlib
import os
import time
import logging
from typing import Any
from core.config import config, ensure_security_config

logger = logging.getLogger(__name__)

# --- 密码哈希 (M3) ---------------------------------------------------------
# 标准库 pbkdf2_hmac 实现, 无第三方依赖。存储格式:
#   $pbkdf2-sha256$100000$<salt_hex>$<hash_hex>
# 兼容旧配置: 存储值不带前缀时视为明文 (向后兼容, 登录/改密时自动升级为哈希)。

_PBKDF2_ITERATIONS = 100_000
_PBKDF2_PREFIX = f"$pbkdf2-sha256${_PBKDF2_ITERATIONS}$"


def hash_password(password: str) -> str:
    """生成带随机盐的 pbkdf2-sha256 密码哈希。"""
    salt = os.urandom(16)
    dk = hashlib.pbkdf2_hmac(
        "sha256", password.encode("utf-8"), salt, _PBKDF2_ITERATIONS
    )
    return f"{_PBKDF2_PREFIX}{salt.hex()}${dk.hex()}"


def verify_password(password: str, stored: str) -> bool:
    """校验密码; 旧版明文配置自动兼容 (常数时间比较)。"""
    if not stored:
        return False
    if stored.startswith("$pbkdf2-sha256$"):
        try:
            _, _, iters, salt_hex, hash_hex = stored.split("$", 4)
            dk = hashlib.pbkdf2_hmac(
                "sha256",
                password.encode("utf-8"),
                bytes.fromhex(salt_hex),
                int(iters),
            )
            return hmac.compare_digest(dk.hex(), hash_hex)
        except (ValueError, TypeError):
            return False
    # 旧配置明文密码 (常数时间比较, 避免时序侧信道)
    return hmac.compare_digest(password, stored)


# Cache secret key in memory
_SECRET_KEY = None

def get_secret_key():
    global _SECRET_KEY  # noqa: PLW0603 - 密钥内存缓存单例惯用法
    if _SECRET_KEY:
        return _SECRET_KEY

    # Try to get from config
    s = config.get('global', {}).get('secret_key')

    # If not in loaded config, it might be generated by ensure_security_config
    if not s:
        # This call reads file if needed
        s, _ = ensure_security_config()

    _SECRET_KEY = s
    return _SECRET_KEY

def generate_signed_url_params(song_id: str, ttl_seconds: int = 259200) -> dict:
    """
    Generate sign and expires params for a given song_id.
    Default TTL: 72 hours (3 days).
    """
    secret = get_secret_key()
    expires = int(time.time()) + ttl_seconds

    # Data to sign: "song_id|expires"
    data = f"{song_id}|{expires}"

    signature = hmac.new(
        key=secret.encode('utf-8'),
        msg=data.encode('utf-8'),
        digestmod=hashlib.sha256
    ).hexdigest()

    # Return as dict for easy url construction
    return {
        "id": song_id,
        "sign": signature,
        "expires": str(expires)
    }

def verify_signature(song_id: str, signature: str, expires: str) -> bool:
    """Verify if the signature is valid and not expired."""
    try:
        # 1. Check Expiration
        exp_ts = int(expires)
        if time.time() > exp_ts:
            logger.warning(f"Signature expired for {song_id}")
            return False

        # 2. Re-calculate Signature
        secret = get_secret_key()
        data = f"{song_id}|{expires}"

        expected_sign = hmac.new(
            key=secret.encode('utf-8'),
            msg=data.encode('utf-8'),
            digestmod=hashlib.sha256
        ).hexdigest()

        # 3. Compare (Constant time comparison)
        if hmac.compare_digest(expected_sign, signature):
            return True

        logger.warning(f"Signature mismatch for {song_id}")
        return False

    except Exception as e:
        logger.error(f"Signature verification error: {e}")
        return False


# --- Configuration Sanitization (C-01) -------------------------------------

#: 敏感键关键词。凡是键名（转小写后）**包含**其中任意一项，其值都会被脱敏。
#: 之所以用 "包含" 而非 "全等"，是为了覆盖 corp_secret / wecom_bot_token / db_password
#: 这类带前后缀的变体命名。
SENSITIVE_KEY_MARKERS = (
    "secret_key",
    "secret",
    "token",
    "password",
    "corpsecret",
    "bot_token",
    "access_token",
    "refresh_token",
    "api_key",
    "client_secret",
    "cookie",
    "authorization",
)

#: 脱敏后的占位值。前端据此判断"该字段已设置但不予回显"。
REDACTED_PLACEHOLDER = "***redacted***"


def is_sensitive_key(key: Any) -> bool:
    """判断某个配置键名是否属于敏感字段。

    Args:
        key: 配置字典的键，通常为 str；非字符串键一律视为不敏感。

    Returns:
        True 表示该键的值需要脱敏。
    """
    if not isinstance(key, str):
        return False
    lowered = key.lower()
    return any(marker in lowered for marker in SENSITIVE_KEY_MARKERS)


def sanitize_config(cfg: Any) -> Any:
    """递归深拷贝配置并脱敏所有敏感字段。

    仅用于「读回显」响应，**不得**用于持久化写入路径，否则会把占位符写进配置。

    行为说明：
        - dict: 逐键递归；命中敏感键的值替换为占位符（值为空/None 时保持空，
          以便前端正确显示"未配置"状态）。
        - list / tuple: 逐元素递归，保持原有容器类型（tuple 返回 list 以保证 JSON 可序列化）。
        - 其它标量: 原样返回。

    Args:
        cfg: 任意配置片段（通常是 ConfigManager 的 _config 顶层字典）。

    Returns:
        脱敏后的**新对象**，原始配置不会被修改。
    """
    if isinstance(cfg, dict):
        sanitized: dict = {}
        for key, value in cfg.items():
            if is_sensitive_key(key):
                # 空值保持空，避免前端把占位符当成"已配置"
                sanitized[key] = REDACTED_PLACEHOLDER if value else value
            else:
                sanitized[key] = sanitize_config(value)
        return sanitized

    if isinstance(cfg, (list, tuple)):
        return [sanitize_config(item) for item in cfg]

    return cfg
