"""add_last_enrich_at_to_song

Revision ID: 56608622def2
Revises: 7caa34b35a43
Create Date: 2026-02-03 11:36:49.620539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56608622def2'
down_revision: Union[str, Sequence[str], None] = '7caa34b35a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_records_unique_key'), table_name='media_records')
    op.drop_table('media_records')
    op.add_column('songs', sa.Column('last_enrich_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'last_enrich_at')
    op.create_table('media_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_key', sa.VARCHAR(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('media_type', sa.VARCHAR(), nullable=False),
    sa.Column('media_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('cover', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('album', sa.VARCHAR(), nullable=True),
    sa.Column('publish_time', sa.DATETIME(), nullable=True),
    sa.Column('local_audio_path', sa.VARCHAR(), nullable=True),
    sa.Column('audio_quality', sa.INTEGER(), nullable=True),
    sa.Column('lyrics', sa.TEXT(), nullable=True),
    sa.Column('lyrics_source', sa.VARCHAR(), nullable=True),
    sa.Column('lyrics_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_url', sa.VARCHAR(), nullable=True),
    sa.Column('found_at', sa.DATETIME(), nullable=True),
    sa.Column('is_pushed', sa.BOOLEAN(), nullable=True),
    sa.Column('push_time', sa.DATETIME(), nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=True),
    sa.Column('extra_sources', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_records_unique_key'), 'media_records', ['unique_key'], unique=1)
    # ### end Alembic commands ###
